import Link from "next/link";


export const metadata = {
    title: "Products Page",
    description: "Generated by create next app",
};

export default function() {
    return (
        <div>
            <h1>Products</h1>
            <Link href={'/products/1?name=f8'}>go to detail</Link>
        </div>
    )
}