version: '3'

services:
  web:
    container_name: web-core
    image: node:18.17.0
    working_dir: /app/241014_store
    volumes:
      - './241014_store:/app/241014_store'
    ports:
      - '3000:3000'
      - '5173:5173'
    command: ['npm', 'run', 'dev']