version: '3'

services:
  web:
    container_name: web-core
    image: node:18.17.0
    working_dir: /app/react_optimizer
    volumes:
      - './react_optimizer:/app/react_optimizer'
    ports:
      - '3000:3000'
      - '5173:5173'
    command: ['npm', 'run', 'dev']